name: child-action-with-output
description: Child Action With Output

outputs:
  done:
    description: "What was done"
    value: ${{ steps.step-one.outputs.done }}

runs:
  using: composite
  steps:
  - name: child step one
    shell: bash
    run: |
      echo "Do some stuff"
      echo "::set-output name=done::stuff"
