name: parse-context-array
description: Parse Context Array

inputs:
  step-two-exit-code:
    required: true

runs:
  using: composite
  steps:
  - name: step one
    id: step-one
    shell: bash
    run: exit 0

  - name: step two
    id: step-two
    shell: bash
    run: exit ${{ inputs.step-two-exit-code }}

  - name: Echo job statuses
    if: always()
    shell: bash
    run: |
      echo ${{ steps.step-one.outcome }}
      echo ${{ steps.step-two.outcome }}

  - name: Evaluate job status
    if: always()
    shell: bash
    run: |
      JOB_STATUS="${{ join(steps.*.outcome, ',') }}"
      if [[ $JOB_STATUS =~ "failure" ]]; then
        echo JOB_STATUS="failure" >> $GITHUB_ENV;
      else
        echo JOB_STATUS="success" >> $GITHUB_ENV;
      fi;

  - name: Report job status
    if: always()
    shell: bash
    run: echo "job status ${{env.JOB_STATUS}}"
