name: parse-context-array
description: Parse Context Array

runs:
  using: composite
  steps:
  - name: step one
    shell: bash
    run: exit 0

  - name: step two
    shell: bash
    run: exit 0

  - name: Evaluate job status
    if: always()
    shell: bash
    run: |
      echo $STEP_OUTCOMES
    env:
      STEP_OUTCOMES: ${{join(steps.*.outcome }, ',')}}
