name: action-with-output-from-env
description: Action With Output From Env

outputs:
  env-url:
    description: "URL from action env var"
    value: ${{ env.URL }}
  output-url:
    description: "URL from step output"
    value: ${{ steps.step-inside-action.outputs.step-url }}

runs:
  using: composite
  steps:
  - name: step inside action
    id: step-inside-action
    shell: bash
    run: |
      echo "URL is https://example.com"
      echo "URL=https://example.com" >> $GITHUB_ENV
      echo "::set-output name=step-url::https://example.com"

  - name: echo step inside action output
    id: echo-step-inside-action-output
    shell: bash
    run: echo ${{ steps.step-inside-action.outputs.step-url }}
