name: action-with-output-from-env
description: Action With Output From Env

outputs:
  url:
    description: "Deployment URL"
    value: ${{ env.URL }}

runs:
  using: composite
  steps:
  - name: step inside action
    id: step-inside-action
    shell: bash
    run: |
      echo "URL is https://example.com"
      echo "URL=https://example.com" >> $GITHUB_ENV
