name: AzureOidc

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  azure:
    name: Azure Oidc
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: PS Command
      shell: pwsh
      run:
        Write-Output "Subscription has $((Get-AzResourceGroup).Count) resource groups"