name: AzureOidc

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  azure:
    name: Azure Oidc
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: PS Command
      shell: pwsh
      run:
        Write-Output "Subscription has $((Get-AzResourceGroup).Count) resource groups"