name: AzureOidc

on:
  workflow_dispatch:
  push:

jobs:
  azure:
    name: Azure Oidc
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}