name: AzureOidc

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  azure:
    name: Azure Oidc
    environment: Pay-As-You-Go
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v2
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - name: Azure PowerShell script
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          Write-Output "Subscription has $((Get-AzResourceGroup).Count) resource groups"
