name: DeploymentStatusUpdate

on: 
  pull_request:
  workflow_dispatch:
    inputs:
      fail-deployment:
        type: boolean
        default: false

jobs:
  test:
    name: Deployment Status Update
    environment:
      name: JobDefinedEnvironment
      url: https://example.com
    runs-on: ubuntu-latest
    steps:
    - name: Do some stuff
      shell: bash
      run: |
        echo "Do some stuff $(date +%T)"
        sleep 30
        echo "Done some stuff $(date +%T)"

    - name: Fail deployment
      if: ${{ github.event.inputs.fail-deployment == 'true' }}
      shell: bash
      run: exit 1

