name: MatrixConcurrency
concurrency: matrix_concurrency_${{ github.ref_name }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-matrix-job:
    name: Pre Matrix
    concurrency: matrix_concurrency_external_${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Do some stuff in outside the matrix
        run: |
          echo "Do some stuff $(date +%T)"
          sleep 30
          echo "Done some stuff $(date +%T)"

  matrix-job:
    name: Matrix Concurrency
    runs-on: ubuntu-latest
    concurrency: matrix_concurrency_${{ github.ref_name }}
    strategy:
      matrix:
        environment: [qa,staging,production,sandbox]
      max-parallel: 1
    steps:
      - name: Do some stuff in ${{ matrix.environment }}
        run: |
          echo "Do some stuff $(date +%T)"
          sleep 5
          if [[ ${{ matrix.environment }} == "staging" ]]; then
            exit 1;
          fi;
          echo "Done some stuff $(date +%T)"
