name: MonitorRateLimit

on: 
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Monitor Rate Limit
    runs-on: ubuntu-latest
    steps:
    - name: Get Rate Limit One
      run: 'curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit'
