name: ParseContextArray

on: 
  workflow_dispatch:
    inputs:
      step-two-exit-code:
        type: number
        default: 0

jobs:
  test:
    name: Parse Context Array
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Parse Context Array
        uses: ./.github/actions/parse-context-array/
        with:
          step-two-exit-code: ${{ github.event.inputs.step-two-exit-code }}
