name: PassActionOutputToJobEnvironment

on: 
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Pass Action Output To Job Environment
    environment:
      name: ${{ matrix.environment }}
      url: ${{ env.URL }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Test,Staging]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Step Outputs In Action
        id: call-action-step
        uses: ./.github/actions/action-with-output-from-env/
        with: 
          environment: ${{ matrix.environment }}

      - name: Echo Output
        run: |
          echo ${{ steps.step-inside-action.outputs.env-url }}
          echo ${{ steps.call-action-step.outputs.env-url }}
          echo ${{ env.URL }}
          echo ${{ steps.step-inside-action.outputs.output-url }}
          echo ${{ steps.call-action-step.outputs.output-url }}
