name: PushGitTag

on: 
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Push Git Tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag

    - uses: actions-ecosystem/action-bump-semver@v1
      id: bump-semver
      with:
        current_version: ${{ steps.get-latest-tag.outputs.tag }}
        level: minor
