name: WorkflowDispatchBranchesFilter

on: 
  workflow_dispatch:
    branches:
      - main

jobs:
    test:
        name: Test Job
        runs-on: ubuntu-latest
        steps:
        - name: Do some stuff
          run: |
            echo "Do some stuff $(date +%T)"